spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/query_db
spring.datasource.username=root
spring.datasource.password=Srinithi@8287



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.data.redis.url=redis://default:06sF3OkmLLIUtdUpRm5zVBvwJ1hxW9Xs@redis-12326.crce283.ap-south-1-2.ec2.cloud.redislabs.com:12326